risky: false
version: 8.1
preset: psr12
enabled:
  # Risky Fixers
  # - declare_strict_types
  # - void_return
  - ordered_class_elements
  - linebreak_after_opening_tag
  - single_quote
  - no_blank_lines_after_phpdoc
  - unary_operator_spaces
  - no_useless_else
  - no_useless_return
  - trailing_comma_in_multiline_array
  - concat_without_spaces
finder:
  exclude:
    - "tests"
    - "public"
