risky: false
preset: psr12
enabled:
  # Risky Fixers
  # - declare_strict_types
  # - void_return
  - ordered_class_elements
  - linebreak_after_opening_tag
  - single_quote
  - no_blank_lines_after_phpdoc
  - no_useless_else
  - no_useless_return
  - trailing_comma_in_multiline_array
finder:
  exclude:
    - "Tests"
    - "installer/Application/Common/resources/tests"
    - "installer/Module/RoadRunnerBridge/resources/config"
