name: phpunit

on:
  push:
    branches:
      - installer
  pull_request:
    branches:
      - installer

  workflow_dispatch:

defaults:
  run:
    working-directory: installer

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}, ${{ matrix.stability }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        os: ['ubuntu-latest']
        stability: ['prefer-lowest', 'prefer-stable']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_sqlite, sockets, grpc
          tools: pecl

      - name: Validate Composer
        run: composer validate

      - name: 📥 Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.stability }}
          working-directory: installer

      - name: Execute Tests
        run: composer test
